# GNU Make project makefile autogenerated by Premake

ifndef config
  config=default
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = .
TARGET = $(TARGETDIR)/librive_sheenbidi.a
OBJDIR = obj/default/rive_sheenbidi
DEFINES += -DWITH_RIVE_TEXT -DWITH_RIVE_LAYOUT -DDEBUG -DRIVE_MACOSX
INCLUDES += -I../../dependencies/B223B0E94/SheenBidi-2.6/Headers
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g -w -fobjc-arc -mmacosx-version-min=11.0 -Wall -ansi -pedantic
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g -w -std=c++17 -fno-exceptions -fno-rtti -fobjc-arc -mmacosx-version-min=11.0 -Wall -ansi -pedantic
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
ALL_LDFLAGS += $(LDFLAGS) -r
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/BidiChain.o
GENERATED += $(OBJDIR)/BidiTypeLookup.o
GENERATED += $(OBJDIR)/BracketQueue.o
GENERATED += $(OBJDIR)/GeneralCategoryLookup.o
GENERATED += $(OBJDIR)/IsolatingRun.o
GENERATED += $(OBJDIR)/LevelRun.o
GENERATED += $(OBJDIR)/PairingLookup.o
GENERATED += $(OBJDIR)/RunQueue.o
GENERATED += $(OBJDIR)/SBAlgorithm.o
GENERATED += $(OBJDIR)/SBBase.o
GENERATED += $(OBJDIR)/SBCodepointSequence.o
GENERATED += $(OBJDIR)/SBLine.o
GENERATED += $(OBJDIR)/SBLog.o
GENERATED += $(OBJDIR)/SBMirrorLocator.o
GENERATED += $(OBJDIR)/SBParagraph.o
GENERATED += $(OBJDIR)/SBScriptLocator.o
GENERATED += $(OBJDIR)/ScriptLookup.o
GENERATED += $(OBJDIR)/ScriptStack.o
GENERATED += $(OBJDIR)/StatusStack.o
OBJECTS += $(OBJDIR)/BidiChain.o
OBJECTS += $(OBJDIR)/BidiTypeLookup.o
OBJECTS += $(OBJDIR)/BracketQueue.o
OBJECTS += $(OBJDIR)/GeneralCategoryLookup.o
OBJECTS += $(OBJDIR)/IsolatingRun.o
OBJECTS += $(OBJDIR)/LevelRun.o
OBJECTS += $(OBJDIR)/PairingLookup.o
OBJECTS += $(OBJDIR)/RunQueue.o
OBJECTS += $(OBJDIR)/SBAlgorithm.o
OBJECTS += $(OBJDIR)/SBBase.o
OBJECTS += $(OBJDIR)/SBCodepointSequence.o
OBJECTS += $(OBJDIR)/SBLine.o
OBJECTS += $(OBJDIR)/SBLog.o
OBJECTS += $(OBJDIR)/SBMirrorLocator.o
OBJECTS += $(OBJDIR)/SBParagraph.o
OBJECTS += $(OBJDIR)/SBScriptLocator.o
OBJECTS += $(OBJDIR)/ScriptLookup.o
OBJECTS += $(OBJDIR)/ScriptStack.o
OBJECTS += $(OBJDIR)/StatusStack.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking rive_sheenbidi
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning rive_sheenbidi
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/BidiChain.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/BidiChain.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BidiTypeLookup.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/BidiTypeLookup.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BracketQueue.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/BracketQueue.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GeneralCategoryLookup.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/GeneralCategoryLookup.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IsolatingRun.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/IsolatingRun.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LevelRun.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/LevelRun.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PairingLookup.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/PairingLookup.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RunQueue.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/RunQueue.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SBAlgorithm.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/SBAlgorithm.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SBBase.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/SBBase.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SBCodepointSequence.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/SBCodepointSequence.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SBLine.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/SBLine.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SBLog.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/SBLog.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SBMirrorLocator.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/SBMirrorLocator.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SBParagraph.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/SBParagraph.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SBScriptLocator.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/SBScriptLocator.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ScriptLookup.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/ScriptLookup.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ScriptStack.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/ScriptStack.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StatusStack.o: ../../dependencies/B223B0E94/SheenBidi-2.6/Source/StatusStack.c
	@echo "$(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif