# GNU Make project makefile autogenerated by Premake

ifndef config
  config=default
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = .
TARGET = $(TARGETDIR)/librive_harfbuzz.a
OBJDIR = obj/default/rive_harfbuzz
DEFINES += -DWITH_RIVE_TEXT -DWITH_RIVE_LAYOUT -DDEBUG -DRIVE_MACOSX -DHB_ONLY_ONE_SHAPER -DHAVE_OT -DHB_NO_FALLBACK_SHAPE -DHB_NO_WIN1256 -DHB_NO_EXTERN_HELPERS -DHB_DISABLE_DEPRECATED -DHB_NO_COLOR -DHB_NO_BITMAP -DHB_NO_BUFFER_SERIALIZE -DHB_NO_BUFFER_VERIFY -DHB_NO_BUFFER_MESSAGE -DHB_NO_SETLOCALE -DHB_NO_VERTICAL -DHB_NO_LAYOUT_COLLECT_GLYPHS -DHB_NO_LAYOUT_RARELY_USED -DHB_NO_LAYOUT_UNUSED -DHB_NO_OT_FONT_GLYPH_NAMES -DHB_NO_PAINT -DHB_NO_MMAP -DHB_NO_META -DHAVE_CORETEXT
INCLUDES += -I../.. -I../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src -I../../dependencies
FORCE_INCLUDE += -include rive_harfbuzz_renames.h
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -Werror -g -w -fobjc-arc -mmacosx-version-min=11.0 -Werror=format -Wimplicit-int-conversion -Werror=vla
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -Werror -g -w -std=c++17 -fno-exceptions -fno-rtti -fobjc-arc -mmacosx-version-min=11.0 -Werror=format -Wimplicit-int-conversion -Werror=vla
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
ALL_LDFLAGS += $(LDFLAGS)
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/gsubgpos-context.o
GENERATED += $(OBJDIR)/hb-aat-layout.o
GENERATED += $(OBJDIR)/hb-aat-map.o
GENERATED += $(OBJDIR)/hb-blob.o
GENERATED += $(OBJDIR)/hb-buffer-serialize.o
GENERATED += $(OBJDIR)/hb-buffer-verify.o
GENERATED += $(OBJDIR)/hb-buffer.o
GENERATED += $(OBJDIR)/hb-common.o
GENERATED += $(OBJDIR)/hb-coretext-font.o
GENERATED += $(OBJDIR)/hb-coretext-shape.o
GENERATED += $(OBJDIR)/hb-draw.o
GENERATED += $(OBJDIR)/hb-face.o
GENERATED += $(OBJDIR)/hb-font.o
GENERATED += $(OBJDIR)/hb-map.o
GENERATED += $(OBJDIR)/hb-number.o
GENERATED += $(OBJDIR)/hb-ot-cff1-table.o
GENERATED += $(OBJDIR)/hb-ot-cff2-table.o
GENERATED += $(OBJDIR)/hb-ot-color.o
GENERATED += $(OBJDIR)/hb-ot-face.o
GENERATED += $(OBJDIR)/hb-ot-font.o
GENERATED += $(OBJDIR)/hb-ot-layout.o
GENERATED += $(OBJDIR)/hb-ot-map.o
GENERATED += $(OBJDIR)/hb-ot-math.o
GENERATED += $(OBJDIR)/hb-ot-meta.o
GENERATED += $(OBJDIR)/hb-ot-metrics.o
GENERATED += $(OBJDIR)/hb-ot-name.o
GENERATED += $(OBJDIR)/hb-ot-shape-fallback.o
GENERATED += $(OBJDIR)/hb-ot-shape-normalize.o
GENERATED += $(OBJDIR)/hb-ot-shape.o
GENERATED += $(OBJDIR)/hb-ot-shaper-arabic.o
GENERATED += $(OBJDIR)/hb-ot-shaper-default.o
GENERATED += $(OBJDIR)/hb-ot-shaper-hangul.o
GENERATED += $(OBJDIR)/hb-ot-shaper-hebrew.o
GENERATED += $(OBJDIR)/hb-ot-shaper-indic-table.o
GENERATED += $(OBJDIR)/hb-ot-shaper-indic.o
GENERATED += $(OBJDIR)/hb-ot-shaper-khmer.o
GENERATED += $(OBJDIR)/hb-ot-shaper-myanmar.o
GENERATED += $(OBJDIR)/hb-ot-shaper-syllabic.o
GENERATED += $(OBJDIR)/hb-ot-shaper-thai.o
GENERATED += $(OBJDIR)/hb-ot-shaper-use.o
GENERATED += $(OBJDIR)/hb-ot-shaper-vowel-constraints.o
GENERATED += $(OBJDIR)/hb-ot-tag.o
GENERATED += $(OBJDIR)/hb-ot-var.o
GENERATED += $(OBJDIR)/hb-outline.o
GENERATED += $(OBJDIR)/hb-paint-extents.o
GENERATED += $(OBJDIR)/hb-paint.o
GENERATED += $(OBJDIR)/hb-set.o
GENERATED += $(OBJDIR)/hb-shape-plan.o
GENERATED += $(OBJDIR)/hb-shape.o
GENERATED += $(OBJDIR)/hb-shaper.o
GENERATED += $(OBJDIR)/hb-static.o
GENERATED += $(OBJDIR)/hb-style.o
GENERATED += $(OBJDIR)/hb-subset-cff-common.o
GENERATED += $(OBJDIR)/hb-subset-cff1.o
GENERATED += $(OBJDIR)/hb-subset-cff2.o
GENERATED += $(OBJDIR)/hb-subset-input.o
GENERATED += $(OBJDIR)/hb-subset-plan.o
GENERATED += $(OBJDIR)/hb-subset-repacker.o
GENERATED += $(OBJDIR)/hb-subset.o
GENERATED += $(OBJDIR)/hb-ucd.o
GENERATED += $(OBJDIR)/hb-unicode.o
OBJECTS += $(OBJDIR)/gsubgpos-context.o
OBJECTS += $(OBJDIR)/hb-aat-layout.o
OBJECTS += $(OBJDIR)/hb-aat-map.o
OBJECTS += $(OBJDIR)/hb-blob.o
OBJECTS += $(OBJDIR)/hb-buffer-serialize.o
OBJECTS += $(OBJDIR)/hb-buffer-verify.o
OBJECTS += $(OBJDIR)/hb-buffer.o
OBJECTS += $(OBJDIR)/hb-common.o
OBJECTS += $(OBJDIR)/hb-coretext-font.o
OBJECTS += $(OBJDIR)/hb-coretext-shape.o
OBJECTS += $(OBJDIR)/hb-draw.o
OBJECTS += $(OBJDIR)/hb-face.o
OBJECTS += $(OBJDIR)/hb-font.o
OBJECTS += $(OBJDIR)/hb-map.o
OBJECTS += $(OBJDIR)/hb-number.o
OBJECTS += $(OBJDIR)/hb-ot-cff1-table.o
OBJECTS += $(OBJDIR)/hb-ot-cff2-table.o
OBJECTS += $(OBJDIR)/hb-ot-color.o
OBJECTS += $(OBJDIR)/hb-ot-face.o
OBJECTS += $(OBJDIR)/hb-ot-font.o
OBJECTS += $(OBJDIR)/hb-ot-layout.o
OBJECTS += $(OBJDIR)/hb-ot-map.o
OBJECTS += $(OBJDIR)/hb-ot-math.o
OBJECTS += $(OBJDIR)/hb-ot-meta.o
OBJECTS += $(OBJDIR)/hb-ot-metrics.o
OBJECTS += $(OBJDIR)/hb-ot-name.o
OBJECTS += $(OBJDIR)/hb-ot-shape-fallback.o
OBJECTS += $(OBJDIR)/hb-ot-shape-normalize.o
OBJECTS += $(OBJDIR)/hb-ot-shape.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-arabic.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-default.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-hangul.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-hebrew.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-indic-table.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-indic.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-khmer.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-myanmar.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-syllabic.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-thai.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-use.o
OBJECTS += $(OBJDIR)/hb-ot-shaper-vowel-constraints.o
OBJECTS += $(OBJDIR)/hb-ot-tag.o
OBJECTS += $(OBJDIR)/hb-ot-var.o
OBJECTS += $(OBJDIR)/hb-outline.o
OBJECTS += $(OBJDIR)/hb-paint-extents.o
OBJECTS += $(OBJDIR)/hb-paint.o
OBJECTS += $(OBJDIR)/hb-set.o
OBJECTS += $(OBJDIR)/hb-shape-plan.o
OBJECTS += $(OBJDIR)/hb-shape.o
OBJECTS += $(OBJDIR)/hb-shaper.o
OBJECTS += $(OBJDIR)/hb-static.o
OBJECTS += $(OBJDIR)/hb-style.o
OBJECTS += $(OBJDIR)/hb-subset-cff-common.o
OBJECTS += $(OBJDIR)/hb-subset-cff1.o
OBJECTS += $(OBJDIR)/hb-subset-cff2.o
OBJECTS += $(OBJDIR)/hb-subset-input.o
OBJECTS += $(OBJDIR)/hb-subset-plan.o
OBJECTS += $(OBJDIR)/hb-subset-repacker.o
OBJECTS += $(OBJDIR)/hb-subset.o
OBJECTS += $(OBJDIR)/hb-ucd.o
OBJECTS += $(OBJDIR)/hb-unicode.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking rive_harfbuzz
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning rive_harfbuzz
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/gsubgpos-context.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/graph/gsubgpos-context.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-aat-layout.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-aat-layout.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-aat-map.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-aat-map.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-blob.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-blob.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-buffer-serialize.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-buffer-serialize.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-buffer-verify.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-buffer-verify.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-buffer.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-buffer.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-common.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-common.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-coretext-font.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-coretext-font.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-coretext-shape.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-coretext-shape.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-draw.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-draw.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-face.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-face.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-font.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-font.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-map.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-map.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-number.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-number.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-cff1-table.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-cff1-table.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-cff2-table.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-cff2-table.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-color.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-color.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-face.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-face.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-font.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-font.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-layout.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-layout.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-map.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-map.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-math.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-math.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-meta.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-meta.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-metrics.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-metrics.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-name.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-name.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shape-fallback.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shape-fallback.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shape-normalize.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shape-normalize.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shape.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shape.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-arabic.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-arabic.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-default.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-default.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-hangul.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-hangul.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-hebrew.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-hebrew.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-indic-table.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-indic-table.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-indic.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-indic.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-khmer.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-khmer.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-myanmar.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-myanmar.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-syllabic.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-syllabic.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-thai.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-thai.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-use.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-use.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-shaper-vowel-constraints.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-shaper-vowel-constraints.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-tag.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-tag.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ot-var.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ot-var.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-outline.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-outline.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-paint-extents.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-paint-extents.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-paint.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-paint.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-set.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-set.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-shape-plan.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-shape-plan.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-shape.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-shape.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-shaper.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-shaper.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-static.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-static.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-style.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-style.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-subset-cff-common.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-subset-cff-common.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-subset-cff1.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-subset-cff1.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-subset-cff2.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-subset-cff2.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-subset-input.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-subset-input.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-subset-plan.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-subset-plan.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-subset-repacker.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-subset-repacker.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-subset.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-subset.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-ucd.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-ucd.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/hb-unicode.o: ../../dependencies/25A248FF7/harfbuzz-rive_10.1.0/src/hb-unicode.cc
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif