# GNU Make project makefile autogenerated by Premake

ifndef config
  config=default
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = .
TARGET = $(TARGETDIR)/librive_yoga.a
OBJDIR = obj/default/rive_yoga
DEFINES += -DWITH_RIVE_TEXT -DWITH_RIVE_LAYOUT -DRELEASE -DNDEBUG -DRIVE_MACOSX -DYOGA_EXPORT=
INCLUDES += -I../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1 -I../../dependencies
FORCE_INCLUDE += -include rive_yoga_renames.h
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -w -flto=full -fobjc-arc -mmacosx-version-min=11.0
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -w -std=c++17 -fno-exceptions -fno-rtti -flto=full -fobjc-arc -mmacosx-version-min=11.0
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
ALL_LDFLAGS += $(LDFLAGS) -flto=full
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/Utils.o
GENERATED += $(OBJDIR)/YGConfig.o
GENERATED += $(OBJDIR)/YGEnums.o
GENERATED += $(OBJDIR)/YGLayout.o
GENERATED += $(OBJDIR)/YGNode.o
GENERATED += $(OBJDIR)/YGNodePrint.o
GENERATED += $(OBJDIR)/YGStyle.o
GENERATED += $(OBJDIR)/YGValue.o
GENERATED += $(OBJDIR)/Yoga.o
GENERATED += $(OBJDIR)/event.o
GENERATED += $(OBJDIR)/log.o
OBJECTS += $(OBJDIR)/Utils.o
OBJECTS += $(OBJDIR)/YGConfig.o
OBJECTS += $(OBJDIR)/YGEnums.o
OBJECTS += $(OBJDIR)/YGLayout.o
OBJECTS += $(OBJDIR)/YGNode.o
OBJECTS += $(OBJDIR)/YGNodePrint.o
OBJECTS += $(OBJDIR)/YGStyle.o
OBJECTS += $(OBJDIR)/YGValue.o
OBJECTS += $(OBJDIR)/Yoga.o
OBJECTS += $(OBJDIR)/event.o
OBJECTS += $(OBJDIR)/log.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking rive_yoga
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning rive_yoga
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/Utils.o: ../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1/yoga/Utils.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/YGConfig.o: ../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1/yoga/YGConfig.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/YGEnums.o: ../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1/yoga/YGEnums.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/YGLayout.o: ../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1/yoga/YGLayout.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/YGNode.o: ../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1/yoga/YGNode.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/YGNodePrint.o: ../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1/yoga/YGNodePrint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/YGStyle.o: ../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1/yoga/YGStyle.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/YGValue.o: ../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1/yoga/YGValue.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Yoga.o: ../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1/yoga/Yoga.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/event.o: ../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1/yoga/event/event.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/log.o: ../../dependencies/A8B3A2650/yoga-rive_changes_v2_0_1_1/yoga/log.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif